### PR TITLE
Fix statement

### PR DESCRIPTION
**Pull request by yongpingchen**

### CODE REVIEW

**Comment by satoshikumano** [comment]
@yongpingchen 
There's no initializer of Range takes the both arguments of lowerLimit & upperLimit.
Range clause can be used to describe the condition of <, <=, >, <= and [], [), (], ().
Where [], [), (], () indicates [interval](https://en.wikipedia.org/wiki/Interval_%28mathematics%29)

**Comment by satoshikumano** [comment]
Also from the meaning of 'Range', it is bit unclear that it can be used to describe condition <, <=, >, >=.
It is better describe it when you omit upperLimit or lowerLimit, it works as <, <= or >, >= respectively.

**Comment by yongpingchen** [comment]
@satoshikumano could you confirm?

**Comment by yongpingchen** [comment]
Range the name is conflict with iOS standard class, so I changed to RangeClause.

**Pull request merged**
