### PR TITLE
Release/v1.0.0

### PR DESCRIPTION
**Pull request by yongpingchen**
- change licence to Apache 2.0
- update version to 1.0.0
- publish as new library with name `ThingIF`. So that existing users won't be affected by this updates.

### CODE REVIEW

**Comment by dairyo** [comment]
@yongping 

To change framework name, is changing cocoapod name enough? I wonder we need to change some setting in XCode.

What do you think?

**Comment by yongpingchen** [comment]
@shinsuke-nara , what other else need to change?

**Comment by yongpingchen** [comment]
@shinsuke-nara change target to ThingIF, so that the generated framework is `ThingIF.framework`. Please confirm.

**Comment by dairyo** [comment]
@yongpingcheng LGTM

**Review by satoshikumano — COMMENTED** [review]
The license is not updated in podspec.

**Pull request merged**
