### PR TITLE
Implement getTrigger

### PR DESCRIPTION
**Pull request by dairyo**
* Move `ThingIFAPI.getTrigger` from ThingIFAPI.swift to ThingIFAPI+Trigger.swift.
* Following structs adopt `FromJsonObject`
  * Trigger clause classes
  * Predicate classes
  * `Condition`
  * `ServerCode`
  * `Trigger`
* Add small tests
  * Following classes adopt `Equatable` and `ToJsonObject` in test.
    * `Trigger`
    * `Condition`
    * `ServerCode`
    * Predicate classes
* Delete an old test file.

Related PR: #296

### CODE REVIEW

**Review by naoki-akimoto — APPROVED** [review]
LGTM!

**Review by yongpingchen — CHANGES_REQUESTED** [review]
please add test for `SchedulePredicate` and `ScheduleOncePredicate`

**Comment by dairyo** [comment]
@yongpingchen I added 2 test for `SchedulePredicate` and `ScheduleOncePredicate` according to your comment.

I fixed date time in request and response too. It becomes milliseconds from seconds. This is bug fix.

**Review by yongpingchen — APPROVED** [review]
LGTM

**Pull request merged**
