### PR TITLE
Implement EqualClauseInQuery

### PR DESCRIPTION
**Pull request by dairyo**
I implemented `EqualClauseInQuery`.

Related PR: #303

### CODE REVIEW

**Comment by yongpingchen** [comment]
@shinsuke-nara , Did we have old test file ?

**Comment by dairyo** [comment]
@yongpingchen 

Old one is [this](https://github.com/KiiPlatform/thing-if-iOSSDK/blob/impl-equal-query/ThingIFSDK/ThingIFSDKTests-Old/ClauseNSCodingTests.swift)

Old one is only for NSCoding. I increased test for EqualClause. I will increase tests for other clauses.

**Comment by yongpingchen** [comment]
@shinsuke-nara  I see. So please delete the old test in this PR

**Comment by dairyo** [comment]
@yongpingchen Old test has other clauses test. So I want to delete it after I implement all clauses.

What do you think?

**Comment by yongpingchen** [comment]
@shinsuke-nara  what about just delete the old test about `EqualsClauseInQuery`, not the whole file :)

**Comment by dairyo** [comment]
@yongpingchen OK. I did it:+1:

**Pull request merged**
