### PR TITLE
Implement listTrigger

### PR DESCRIPTION
**Pull request by dairyo**
* Move `ThingIFAPI.listTriggers` from ThingIFAPI.swift to ThingIFAPI+Trigger.swift
* Add small test
* Delete an old test file

Related PR: #296

### CODE REVIEW

**Review by yongpingchen — CHANGES_REQUESTED** [review]
can you add Schedule and Schedule once trigger in the test list?

**Review by naoki-akimoto — APPROVED** [review]
except @yongpingchen 's comments. Others are fine.

**Comment by dairyo** [comment]
@yongpingchen Fixed according to your comment. Please confirm.

**Review by yongpingchen — APPROVED** [review]
LGTM

**Pull request merged**
