### PR TITLE
TypedID adapt Hashable.

### PR DESCRIPTION
**Pull request by dairyo**
Related PR: #296

### CODE REVIEW

**Review by yongpingchen — COMMENTED** [review]
I think TypedID should extend `Hashable` interface. 
https://developer.apple.com/reference/swift/hashable

**Comment by dairyo** [comment]
@yongpingchen `NSObject` already extends `Hashable` interface so we can not extends `Hashable` interface again. It causes compile error.

**Comment by yongpingchen** [comment]
@shinsuke-nara  I see. But why should override both hash and hashValue methods. I check from this Post. Seems override one is ok. http://stackoverflow.com/questions/33319959/nsobject-subclass-in-swift-hash-vs-hashvalue-isequal-vs

**Comment by dairyo** [comment]
@yongpingchen I remove `==` operator because `==` in `NSObject` calls `isEqual` method. so only `isEqual` method is enough. [Object Comparison section in this document](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH4-ID35) guarantees it.

But I could not find official document about`hashValue` vs `hash` issue. I confirmed that implementing `hash` is enough to use `hashValue` with my examination however, I could not find official document guarantees it.

I think implementing both `hash` and `hashValue` is more safe way. What do you think about this?

**Comment by yongpingchen** [comment]
@shinsuke-nara  I am okay with the decision.

**Review by yongpingchen — APPROVED** [review]
LGTM

**Pull request merged**
