### PR TITLE
Added triggersWhat.

### PR DESCRIPTION
**Pull request by satoshikumano**

### CODE REVIEW

**Comment by satoshikumano** [comment]
triggersWhat field is introduced and its a mandatory field.

**Comment by yongpingchen** [comment]
@satoshikumano do we need `triggerWhat` field in `Trigger` class ?

**Comment by yongpingchen** [comment]
If `triggerWhat` field is only for postNewTrigger this time, then this PR is fine to me :)

**Comment by satoshikumano** [comment]
Decided to add triggersWhat in patch request.

There's glitch in server side without the field.
https://github.com/KiiCorp/iot-cloud-api/issues/93

**Comment by yongpingchen** [comment]
Thanks. It looks fine to me

**Pull request merged**
